#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Verify and repair DELFIN installation on BwUniCluster 3.0
#
# Checks: OpenMPI, ORCA, Python venv, DELFIN CLI, directories
# Repairs: recreates venv if needed, reinstalls DELFIN, fixes env
# ============================================================================

DELFIN_REPO="${DELFIN_REPO:-$HOME/software/delfin}"
DELFIN_REPO_URL="${DELFIN_REPO_URL:-https://github.com/ComPlat/DELFIN.git}"
ORCA_TARBALL="${ORCA_TARBALL:-$HOME/orca_6_1_1_linux_x86-64_shared_openmpi418_avx2.tar.xz}"
ORCA_DIR="${ORCA_DIR:-$HOME/software/orca_6_1_1_linux_x86-64_shared_openmpi418_avx2}"
OPENMPI_PREFIX="${OPENMPI_PREFIX:-$HOME/software/openmpi-4.1.8}"
DELFIN_AUTO_ACTIVATE_VENV="${DELFIN_AUTO_ACTIVATE_VENV:-1}"
REQUIRE_ORCA_PLOT="${REQUIRE_ORCA_PLOT:-1}"

log() { printf "[verify] %s\n" "$*"; }
err() { printf "[verify][error] %s\n" "$*" >&2; }

find_orca_dir() {
  if [ -x "$ORCA_DIR/orca" ]; then
    return 0
  fi
  local detected
  detected="$(find "$HOME/software" -maxdepth 3 -type f -name orca 2>/dev/null | head -n1 || true)"
  if [ -n "$detected" ]; then
    ORCA_DIR="$(dirname "$detected")"
    log "Detected ORCA directory: $ORCA_DIR"
  fi
  [ -x "$ORCA_DIR/orca" ]
}

ensure_delfin_env_sourced() {
  local target="$1"
  local source_line='source "$HOME/.delfin_env.sh"'
  if [ ! -f "$target" ]; then
    touch "$target"
  fi
  if ! grep -Fq "$source_line" "$target" 2>/dev/null; then
    printf "\n# DELFIN environment\n%s\n" "$source_line" >> "$target"
    log "Added source \$HOME/.delfin_env.sh to $target"
  else
    log "$target already sources ~/.delfin_env.sh"
  fi
}

if ! command -v module >/dev/null 2>&1; then
  err "'module' command not found. Run this on BwUniCluster login node."
  exit 1
fi

# ---- Check directories ----
log "Checking directories"
mkdir -p "$HOME/software" "$HOME/calc" "$HOME/archive"

# ---- Check OpenMPI ----
log "Checking OpenMPI"
if [ ! -x "$OPENMPI_PREFIX/bin/mpirun" ]; then
  err "OpenMPI not found at $OPENMPI_PREFIX"
  err "Run install script to build OpenMPI."
  exit 2
fi

# ---- Check ORCA ----
log "Checking ORCA"
if [ ! -x "$ORCA_DIR/orca" ]; then
  if [ -f "$ORCA_TARBALL" ]; then
    log "Extracting ORCA from $ORCA_TARBALL into $HOME/software"
    mkdir -p "$HOME/software"
    tar xf "$ORCA_TARBALL" -C "$HOME/software"
  else
    err "ORCA tarball missing: $ORCA_TARBALL"
    exit 3
  fi
fi

if ! find_orca_dir; then
  err "ORCA binary not found after extraction."
  exit 4
fi

if [ "$REQUIRE_ORCA_PLOT" = "1" ] && [ ! -x "$ORCA_DIR/orca_plot" ]; then
  err "orca_plot not found at $ORCA_DIR/orca_plot"
  exit 5
fi

# ---- Check/repair DELFIN repo ----
log "Checking DELFIN repo"
if [ ! -d "$DELFIN_REPO" ]; then
  log "Cloning DELFIN into $DELFIN_REPO"
  git clone "$DELFIN_REPO_URL" "$DELFIN_REPO"
fi

# ---- Check/repair venv ----
log "Checking venv"
module purge
module load devel/python/3.11.7-gnu-14.2

if [ ! -d "$DELFIN_REPO/.venv" ]; then
  python3 -m venv "$DELFIN_REPO/.venv"
else
  if [ ! -f "$DELFIN_REPO/.venv/pyvenv.cfg" ] || ! grep -q "version = 3.11" "$DELFIN_REPO/.venv/pyvenv.cfg"; then
    log "Recreating venv with Python 3.11"
    rm -rf "$DELFIN_REPO/.venv"
    python3 -m venv "$DELFIN_REPO/.venv"
  fi
fi

log "Repairing venv"
# shellcheck disable=SC1090
source "$DELFIN_REPO/.venv/bin/activate"
python -m pip install --upgrade pip wheel
python -m pip install -e "$DELFIN_REPO"

# ---- Regenerate shell env ----
log "Updating shell environment"
ENV_FILE="$HOME/.delfin_env.sh"
cat > "$ENV_FILE" <<EOF
# Auto-generated by verify_delfin_bwu.sh
export DELFIN_REPO="$DELFIN_REPO"
export OPENMPI_PREFIX="$OPENMPI_PREFIX"
export ORCA_DIR="$ORCA_DIR"
export ORCA_BASE="$ORCA_DIR"
export ORCA_PLOT="$ORCA_DIR/orca_plot"
export PATH="$OPENMPI_PREFIX/bin:$ORCA_DIR:\$PATH"
export LD_LIBRARY_PATH="$OPENMPI_PREFIX/lib:$ORCA_DIR:\${LD_LIBRARY_PATH:-}"
export DELFIN_AUTO_ACTIVATE_VENV="\${DELFIN_AUTO_ACTIVATE_VENV:-$DELFIN_AUTO_ACTIVATE_VENV}"
if [ "\${DELFIN_AUTO_ACTIVATE_VENV}" = "1" ] \
   && [ -z "\${VIRTUAL_ENV:-}" ] \
   && [ -d "$DELFIN_REPO/.venv" ] \
   && [ -z "\${VSCODE_PID:-}" ] \
   && [ "\${TERM_PROGRAM:-}" != "vscode" ]; then
  source "$DELFIN_REPO/.venv/bin/activate"
fi
EOF
ensure_delfin_env_sourced "$HOME/.bashrc"
ensure_delfin_env_sourced "$HOME/.profile"

log "orca_plot check"
if [ -x "$ORCA_DIR/orca_plot" ]; then
  log "orca_plot available at $ORCA_DIR/orca_plot"
else
  log "orca_plot not found (check ORCA install)"
fi

log ""
log "Verification complete. Run: source ~/.bashrc"
